name: build

on:
  push:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Checkout
        uses: actions/checkout@v1

      - name: Test
        run: |
          go fmt $(go list ./...)
          go vet $(go list ./...)
          unset "${!CI@}"
          CGO_ENABLED=1 go test -p 1 -mod=readonly -race -coverprofile=.testCoverage.txt -covermode=atomic -coverpkg=$(go list ./... | tr '\n' , | sed 's/,$//') ./...
          go tool cover -html=.testCoverage.txt -o coverage.html
          go tool cover -func=.testCoverage.txt

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: ./coverage.html